### ISSUE TITLE
[PE-D] Multiple Book Return

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-1/tp#154]
Patron 1 has 3 books borrowed.

![1.png](https://raw.githubusercontent.com/nnmoq/ped/main/files/28cefdab-558e-447f-9e1b-d3dce8c331de.png)

When he returns 2 books ```book 3``` and ```book 2```, user wants to enter ```return b/3``` and ```return b/2```.
However, after entering ```return b/3```, the Book List will refresh and show all the Books instead.

![image.png](https://raw.githubusercontent.com/nnmoq/ped/main/files/104d2699-0c2e-4170-b573-c476341c7456.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: nnmoq/ped#1

**Comment by bingsen0806** [comment]
I intentionally made this decision when writing the code, because in some cases it may useful to show the affected books that become available. Nevertheless, I think this suggestion is good and I will change this
