### ISSUE TITLE
[PE-D] Grammatical error

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-1/tp#155]
![Screenshot 2022-04-01 at 2.28.34 PM.png](https://raw.githubusercontent.com/Shivang211/ped/main/files/61343ac3-5896-4915-840e-948efab16416.png)
"you can refer to head to ..", is a grammatical error.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Shivang211/ped#4

**Comment by yl-ang** [comment]
Thank you for raising this, will amend as according
