### ISSUE TITLE
[PE-D] Grammatical Error

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-1/tp#157]
![Screenshot 2022-04-01 at 2.30.27 PM.png](https://raw.githubusercontent.com/Shivang211/ped/main/files/ff560a29-1865-4065-b997-1eecdc1e03cc.png)
Grammatical error in this sentence

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Shivang211/ped#5

**Comment by yl-ang** [comment]
Thank you for raising this!
