### ISSUE TITLE
[PE-D] Wrong error for patron delete even though INDEX is a positive integer and INDEX is invalid

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W14-1/tp#160]
Error for patron delete even though INDEX is a positive integer.

Input: 
patron delete 123123213131231231414151515135143142130948104321438148127364891726341982734618927364981726437382192837467382198273461892837461892736491827364

Output:
![image.png](https://raw.githubusercontent.com/ryantanlien/ped/main/files/73106229-0ac8-4d5f-9eb5-3f055cfbc361.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ryantanlien/ped#1

**Comment by bingsen0806** [comment]
duplicate.
