### ISSUE TITLE
[PE-D] Wrong error for book delete even though INDEX is a positive integer and INDEX is invalid

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-1/tp#163]
Error for book delete even though INDEX is a positive integer.

Input:
book delete 123123213131231231414151515135143142130948104321438148127364891726341982734618927364981726437382192837467382198273461892837461892736491827364

Output:

![image.png](https://raw.githubusercontent.com/ryantanlien/ped/main/files/5a21c68b-9939-4ecf-a292-a9035d5195f9.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ryantanlien/ped#2

**Comment by bingsen0806** [comment]
duplicate.
