### ISSUE TITLE
[PE-D] Patron name can be numbers

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-1/tp#177]
The name of a patron can be a number. Books may be named as number but the name of a patron shouldn't be a number.

![image.png](https://raw.githubusercontent.com/nnmoq/ped/main/files/be69811f-5a86-4f63-9d33-40db9626a41f.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: nnmoq/ped#4

**Comment by yl-ang** [comment]
This is not a bug as taking for example one of Elon Musk's children's names goes by ```X Æ A-12```. We want to ensure that these edge cases are properly considered thus we allowed numbers in patron names.
