### ISSUE TITLE
[PE-D] Invalid day date able to be input into borrow command

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-1/tp#184]
Input:
borrow 7 7 99-May-9999

Output:

![image.png](https://raw.githubusercontent.com/ryantanlien/ped/main/files/17fd0a9b-af05-457a-b126-b12653a355a8.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: ryantanlien/ped#11

**Comment by bingsen0806** [comment]
reported by someone else. closing duplicate issues.
