### ISSUE TITLE
[PE-D] Storage - Can change ISBNs of different books to be identical

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W14-1/tp#190]
The json file can be edited to violate the app's constraints.

![Screenshot 2022-04-01 at 3.34.51 PM.png](https://raw.githubusercontent.com/limweiliang/ped/main/files/638c0548-fd46-40c7-bf58-14716a969415.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: limweiliang/ped#8

**Comment by bingsen0806** [comment]
![json-file](https://user-images.githubusercontent.com/71639142/161368512-8995f011-701b-4064-972a-d9a4d59df715.jpg)

Errors related to intentional changing of json files is not a bug, as per the module's stance.
