### ISSUE TITLE
[PE-D] `book add` - book and author name checking is not case-sensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W14-1/tp#193]
`book add` allows me to create books with the same ISBN but with the name and author in a different case

![Screenshot 2022-04-01 at 3.55.47 PM.png](https://raw.githubusercontent.com/limweiliang/ped/main/files/ed3798de-2319-4436-9a2b-ea6ee61df466.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: limweiliang/ped#10

**Comment by bingsen0806** [comment]
![book-name-case-insensitive](https://user-images.githubusercontent.com/71639142/161366683-c8f26244-00c5-4f98-a6f5-07fd48da5cbd.jpg)

This is what is expected of our module. As shown in the screenshot from the module's website. Not a bug.

Also, as specified, in user guide, having multiple copies of the same book with same isbn is allowed, as long as they have the same name and same author set.
